name: omnivision
channels:
  - conda-forge
  - pytorch
  - defaults

dependencies:
  # Base Python
  - python=3.11

  # Core ML frameworks (Mac optimized)
  - pytorch>=2.0.0
  - torchvision>=0.15.0

  # Scientific computing
  - numpy>=1.24.0
  - scipy>=1.11.0
  - matplotlib>=3.7.0

  # Image processing
  - pillow>=9.5.0
  - opencv>=4.8.0

  # Development tools
  - pip
  - jupyter
  - ipython

  # Pip dependencies (not available via conda)
  - pip:
    - transformers>=4.40.0
    - accelerate>=0.21.0
    - torchao>=0.1.0
    - click>=8.1.0
    - tqdm>=4.65.0
    - pydantic>=2.0.0
    - pytest>=7.4.0
    - pytest-cov>=4.1.0
    - gradio>=4.0.0
    - plotly>=5.15.0
    - joblib>=1.3.0
    - datasets>=2.14.0

# Installation instructions:
# conda env create -f environment.yml
# conda activate omnivision

# For updating:
# conda env update -f environment.yml --prune